// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC20Permit$Type } from "./ERC20Permit";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Permit"]: ERC20Permit$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20Permit.sol:ERC20Permit"]: ERC20Permit$Type;
  }
}
