// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { UsingTellor$Type } from "./UsingTellor";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["UsingTellor"]: UsingTellor$Type;
    ["usingtellor/contracts/UsingTellor.sol:UsingTellor"]: UsingTellor$Type;
  }
}
