// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MyToken$Type } from "./MyToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MyToken"]: MyToken$Type;
    ["contracts/MyToken.sol:MyToken"]: MyToken$Type;
  }
}
