// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { ERC20Votes$Type } from "./ERC20Votes";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC20Votes"]: ERC20Votes$Type;
    ["@openzeppelin/contracts/token/ERC20/extensions/ERC20Votes.sol:ERC20Votes"]: ERC20Votes$Type;
  }
}
