// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Autopay$Type } from "./Autopay";
import { ITellor$Type } from "./ITellor";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Autopay"]: Autopay$Type;
    ["ITellor"]: ITellor$Type;
    ["usingtellor/contracts/interface/ITellor.sol:Autopay"]: Autopay$Type;
    ["usingtellor/contracts/interface/ITellor.sol:ITellor"]: ITellor$Type;
  }
}
