// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Time$Type } from "./Time";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Time"]: Time$Type;
    ["@openzeppelin/contracts/utils/types/Time.sol:Time"]: Time$Type;
  }
}
