// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Time$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Time",
  "sourceName": "@openzeppelin/contracts/utils/types/Time.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220744d9bb72144385edfc7dde59f38ad15d8191ee27bd4410502d0398962e6ebf264736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220744d9bb72144385edfc7dde59f38ad15d8191ee27bd4410502d0398962e6ebf264736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Time",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Time$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/types/Time.sol:Time",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Time$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Time",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Time$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/types/Time.sol:Time",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Time$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Time",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Time$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/types/Time.sol:Time",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Time$Type["abi"]>>;
}
