// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Checkpoints$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Checkpoints",
  "sourceName": "@openzeppelin/contracts/utils/structs/Checkpoints.sol",
  "abi": [
    {
      "inputs": [],
      "name": "CheckpointUnorderedInsertion",
      "type": "error"
    }
  ],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ad8e569f0219aede161eae172442433c5ffd3d324df540222b5d9bf1c595eccc64736f6c63430008180033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220ad8e569f0219aede161eae172442433c5ffd3d324df540222b5d9bf1c595eccc64736f6c63430008180033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Checkpoints",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Checkpoints$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/structs/Checkpoints.sol:Checkpoints",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Checkpoints$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Checkpoints",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Checkpoints$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/structs/Checkpoints.sol:Checkpoints",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Checkpoints$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Checkpoints",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Checkpoints$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/structs/Checkpoints.sol:Checkpoints",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Checkpoints$Type["abi"]>>;
}
