// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Ballot$Type } from "./Ballot";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Ballot"]: Ballot$Type;
    ["contracts/Ballot.sol:Ballot"]: Ballot$Type;
  }
}
