// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { MyNFT$Type } from "./MyNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MyNFT"]: MyNFT$Type;
    ["contracts/MyNFT.sol:MyNFT"]: MyNFT$Type;
  }
}
