// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Votes$Type } from "./Votes";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Votes"]: Votes$Type;
    ["@openzeppelin/contracts/governance/utils/Votes.sol:Votes"]: Votes$Type;
  }
}
