// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Nonces$Type } from "./Nonces";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Nonces"]: Nonces$Type;
    ["@openzeppelin/contracts/utils/Nonces.sol:Nonces"]: Nonces$Type;
  }
}
