// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CallOracle$Type } from "./CallOracle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CallOracle"]: CallOracle$Type;
    ["contracts/CallOracle.sol:CallOracle"]: CallOracle$Type;
  }
}
