// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC5805$Type } from "./IERC5805";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC5805"]: IERC5805$Type;
    ["@openzeppelin/contracts/interfaces/IERC5805.sol:IERC5805"]: IERC5805$Type;
  }
}
