// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IERC2362$Type } from "./IERC2362";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC2362"]: IERC2362$Type;
    ["usingtellor/contracts/interface/IERC2362.sol:IERC2362"]: IERC2362$Type;
  }
}
