// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IERC2362$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IERC2362",
  "sourceName": "usingtellor/contracts/interface/IERC2362.sol",
  "abi": [
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "_id",
          "type": "bytes32"
        }
      ],
      "name": "valueFor",
      "outputs": [
        {
          "internalType": "int256",
          "name": "",
          "type": "int256"
        },
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        },
        {
          "internalType": "uint256",
          "name": "",
          "type": "uint256"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IERC2362",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC2362$Type["abi"]>>;
  export function deployContract(
    contractName: "usingtellor/contracts/interface/IERC2362.sol:IERC2362",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IERC2362$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IERC2362",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC2362$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "usingtellor/contracts/interface/IERC2362.sol:IERC2362",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IERC2362$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IERC2362",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC2362$Type["abi"]>>;
  export function getContractAt(
    contractName: "usingtellor/contracts/interface/IERC2362.sol:IERC2362",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IERC2362$Type["abi"]>>;
}
